### ISSUE TITLE
numpydantic F821 undefined name 'x'

### ISSUE THREAD

**Issue by niklastanner** [PyCQA/pyflakes#820]
pyflakes markes the shape-definition of numpydantic as faulty:
```Python
from numpydantic.ndarray import NDArray
from pydantic import BaseModel

class Foo(BaseModel):
    bar: NDArray[Shape["* x"], float]
```

Error message of `pre-commit run --all-files`: 
```Bash
F821 undefined name 'x'
```
Faulty marked part: `Shape["* x"]`

Pre-Commit config:
```YAML
repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        name: "Check: Python Linting"
```

Not sure what other versions I have to pin here or how to get them.
